### ISSUE TITLE
Spago installs old version

### ISSUE THREAD

**Issue by codingedgar** [ursi/purescript-point-free#2]
HI! Amazing lib <3

I know this is probably an issue with spago and not this library, but I guess this was also a good place to ask:

spago keeps installing an old version (0.1.3), is there a way to update the spago snapshot to take the latest version instead of the old one?

In pursuit and github shows the latest version (1.0.0) so i suppose it is there installable

**Comment by ursi** [comment]
This is because I haven't updated it [here](https://github.com/purescript/package-sets/blob/master/src/groups/ursi.dhall#L4). I will get on that :+1:

**Comment by ursi** [comment]
when purescript/package-sets#1056 is merged and a new package set is created, spago will start using 1.0.0

**Comment by codingedgar** [comment]
thank you 🙏
